name: Clear all cache
on:
  workflow_dispatch:

jobs:
  cleanup:
    permissions:
      actions: write
    runs-on: ubuntu-slim
    steps:
      - name: Cleanup
        run: |
          echo "Deleting caches..."
          gh cache delete --succeed-on-no-caches --all
          echo "Done"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
