name: Docker image retention
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every week

jobs:
  clean:
    name: Delete old images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: snok/container-retention-policy@v3.0.1
      with:
        account: user # Or organization name
        token: ${{ secrets.GITHUB_TOKEN }}
        image-names: ${{ github.event.repository.name }}
        cut-off: 2w
        dry-run: false
