name: Auto update Julia dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every week
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    container:
      image: julia:1.8.5
      env:
        JULIA_PKG_PRECOMPILE_AUTO: '0'
        JULIA_NUM_THREADS: 'auto'
    steps:
      - name: Install Git
        run: apt-get update && apt-get install -y --no-install-recommends git
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Julia dependencies
        run: julia --color=yes --project=@. -e 'import Pkg; Pkg.update()'
      # Authenticate using a custom GitHub APP
      # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          title: Julia Dependency Update
          token: ${{ steps.generate-token.outputs.token }}
          labels: |
            automerge
