name: Auto update Julia manifest dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Every week
  push:
    branches:
      - main
    paths:
      - .github/workflows/update-manifest.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_ID: '189113' # https://github.com/apps/wen-wei-s-pr-bot

jobs:
  update-manifest:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Update Julia dependencies
        run: >
          docker run --rm -w /tmp
          -v ${{ github.workspace }}:/tmp
          -e JULIA_PKG_PRECOMPILE_AUTO=0
          julia:latest
          julia --project=@. --color=yes -e 'import Pkg; Pkg.update(; outdated=true)'
      # Authenticate with a custom GitHub APP
      # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
      - name: Generate token for PR
        uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ env.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v8
        with:
          title: Julia Dependency Update
          token: ${{ steps.generate-token.outputs.token }}
          labels: |
            automerge
