name: Auto update Julia dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every week
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'

jobs:
  update-notebook:
    runs-on: ubuntu-latest
    container:
      image: julia:1.8.4
      env:
        JULIA_PKG_PRECOMPILE_AUTO: '0'
    steps:
      - run: apt-get update && apt-get install -y --no-install-recommends git
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Julia dependencies
        run: julia --color=yes --project=@. --threads=auto -e 'import Pkg; Pkg.update()'
      # Authenticate using a custom GitHub APP
      # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          title: Julia Dependency Update
          token: ${{ steps.generate-token.outputs.token }}
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
