name: Auto update Julia dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every week
  push:
    branches:
      - main
    paths:
      - '.github/**Dockerfile'
      - '.github/workflows/update-manifest.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

env:
  DFILE: '.github/Dockerfile'
  IMAGENAME: 'app:test'

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Julia Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ env.DFILE }}
          tags: ${{ env.IMAGENAME }}
          load: true
          target: base
      - name: Update Julia dependencies
        run: >
          docker run --rm
          --workdir=/tmp -v ${{ github.workspace }}:/tmp
          -e JULIA_PKG_PRECOMPILE_AUTO=0
          ${{ env.IMAGENAME }}
          julia --color=yes --threads=auto --project=@. -e "import Pkg; Pkg.update()"
      # Authenticate with a custom GitHub APP
      # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          title: Julia Dependency Update
          token: ${{ steps.generate-token.outputs.token }}
          labels: |
            automerge
